### ISSUE TITLE
Phase one - Groundwork: to-do

### ISSUE THREAD

**Issue by bistaastha** [bistaastha/badging-meta#1]
- Creating user stories (#2)**[May 5 - May 11]**:
  - [x] Applicants (Different for Events and Projects)
  - [x] Reviewers (Similar)
-----
- Roles and permissions (#3)**[May 12 - May 18]**:
  - [x] GitHub permissions associated with each participant in the review
-----
- Working on Event and Project submission and review flows(#4, #5)**[Would be worked on throughout phase one]**:
  - [x] Work out the submission and review flows for Events and Projects and lightly document 
  - [x] Test using mock submissions at certain points(TBD)
-----
- Review Checklists **[Till June 18]**:
  - [x] Events #9 (Multiple - based on applicable metrics)
  - [x] Projects #10 (Singular)
-----
- Guidelines and requirements (#6, #7, #8) **[Till June 20]**:
  - [x] For Applicants (Project Submission)[May 19 - May 23]
  - [x] For Applicants (Event Submission) [Till June 8]
  - [x] For Reviewers (Review)
-----
- Miscellaneous (things to be considered):
  - Badge representation
  - Badge validity
  - Reviewer sign up
  - Applicable Event metrics
  - Unique identifiers for each request?
